### ISSUE TITLE
Method too large

### ISSUE THREAD

**Issue by ghost** [netindev/scuti#6]
[ERROR] Unknown error while executing main thread
org.objectweb.asm.MethodTooLargeException: Method too large: iW.<clinit> ()V
        at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2084)
        at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:447)
        at tk.netindev.scuti.core.Scuti.lambda$4(Scuti.java:183)
        at java.util.HashMap$Values.forEach(HashMap.java:981)
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062)
        at tk.netindev.scuti.core.Scuti.dump(Scuti.java:165)
        at tk.netindev.scuti.core.Scuti.access$3(Scuti.java:159)
        at tk.netindev.scuti.core.Scuti$Runner.run(Scuti.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[22:15:48] [ERROR] Exception message: Method too large: iW.<clinit> ()V

Error when trying to obfuscate a tool that I made.

**Comment by netindev** [comment]
tenta desativar o flow/number obfuscation/misc, pq tudo isso adiciona instrução pro método, não fiz check pra ver se podia adicionar mais instrução.

**Comment by ghost** [comment]
Ok, obrigado. Irei testar.
