### ISSUE TITLE
Unknow Error...

### ISSUE THREAD

**Issue by abodinagdat16** [netindev/scuti#9]
i get:
Corrupting "output.jar"
[17:05:54] [ERROR] Unknown error while executing main thread
java.lang.reflect.InaccessibleObjectException: Unable to make field private java.util.zip.CRC32 java.util.zip.ZipOutputStream.crc accessible: module java.base does not "opens java.util.zip" to unnamed module @28953cb7
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at tk.netindev.scuti.core.util.Util.corruptCRC32(Util.java:64)
        at tk.netindev.scuti.core.Scuti.dump(Scuti.java:163)
        at tk.netindev.scuti.core.Scuti.access$3(Scuti.java:159)
        at tk.netindev.scuti.core.Scuti$Runner.run(Scuti.java:230)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
[17:05:54] [ERROR] Exception message: Unable to make field private java.util.zip.CRC32 java.util.zip.ZipOutputStream.crc accessible: module java.base does not "opens java.util.zip" to unnamed module @28953cb7
[17:05:54] [ERROR] Exiting...

**Comment by netindev** [comment]
don't use any version higher than java 8

**Comment by abodinagdat16** [comment]
i am using java 8😬

**Comment by netindev** [comment]
looks like you aren't

check via java -version via terminal to see your java version

**Comment by abodinagdat16** [comment]
java 8

**Comment by netindev** [comment]
alright, it's possible something changed in the runtime so this problem can be fixed if you disable corrupt_output_stream in the configuration, if somehow didn't work even without corrupt_output_stream disabled, try to disable corrupt_class_names too

**Comment by sadrasirvani** [comment]
hi, is this tool just supporting java 8 ?

**Comment by abodinagdat16** [comment]
yes
